// Code generated by MockGen. DO NOT EDIT.
// Source: event.go

// Package mock_cqrs is a generated GoMock package.
package mock_cqrs

import (
	cqrs "github.com/bounoable/cqrs"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	reflect "reflect"
	time "time"
)

// MockEventData is a mock of EventData interface
type MockEventData struct {
	ctrl     *gomock.Controller
	recorder *MockEventDataMockRecorder
}

// MockEventDataMockRecorder is the mock recorder for MockEventData
type MockEventDataMockRecorder struct {
	mock *MockEventData
}

// NewMockEventData creates a new mock instance
func NewMockEventData(ctrl *gomock.Controller) *MockEventData {
	mock := &MockEventData{ctrl: ctrl}
	mock.recorder = &MockEventDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEventData) EXPECT() *MockEventDataMockRecorder {
	return m.recorder
}

// EventType mocks base method
func (m *MockEventData) EventType() cqrs.EventType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventType")
	ret0, _ := ret[0].(cqrs.EventType)
	return ret0
}

// EventType indicates an expected call of EventType
func (mr *MockEventDataMockRecorder) EventType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventType", reflect.TypeOf((*MockEventData)(nil).EventType))
}

// EventTime mocks base method
func (m *MockEventData) EventTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// EventTime indicates an expected call of EventTime
func (mr *MockEventDataMockRecorder) EventTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventTime", reflect.TypeOf((*MockEventData)(nil).EventTime))
}

// MockEvent is a mock of Event interface
type MockEvent struct {
	ctrl     *gomock.Controller
	recorder *MockEventMockRecorder
}

// MockEventMockRecorder is the mock recorder for MockEvent
type MockEventMockRecorder struct {
	mock *MockEvent
}

// NewMockEvent creates a new mock instance
func NewMockEvent(ctrl *gomock.Controller) *MockEvent {
	mock := &MockEvent{ctrl: ctrl}
	mock.recorder = &MockEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEvent) EXPECT() *MockEventMockRecorder {
	return m.recorder
}

// EventType mocks base method
func (m *MockEvent) EventType() cqrs.EventType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventType")
	ret0, _ := ret[0].(cqrs.EventType)
	return ret0
}

// EventType indicates an expected call of EventType
func (mr *MockEventMockRecorder) EventType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventType", reflect.TypeOf((*MockEvent)(nil).EventType))
}

// EventData mocks base method
func (m *MockEvent) EventData() cqrs.EventData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventData")
	ret0, _ := ret[0].(cqrs.EventData)
	return ret0
}

// EventData indicates an expected call of EventData
func (mr *MockEventMockRecorder) EventData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventData", reflect.TypeOf((*MockEvent)(nil).EventData))
}

// Time mocks base method
func (m *MockEvent) Time() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Time")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Time indicates an expected call of Time
func (mr *MockEventMockRecorder) Time() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Time", reflect.TypeOf((*MockEvent)(nil).Time))
}

// AggregateType mocks base method
func (m *MockEvent) AggregateType() cqrs.AggregateType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateType")
	ret0, _ := ret[0].(cqrs.AggregateType)
	return ret0
}

// AggregateType indicates an expected call of AggregateType
func (mr *MockEventMockRecorder) AggregateType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateType", reflect.TypeOf((*MockEvent)(nil).AggregateType))
}

// AggregateID mocks base method
func (m *MockEvent) AggregateID() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateID")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// AggregateID indicates an expected call of AggregateID
func (mr *MockEventMockRecorder) AggregateID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateID", reflect.TypeOf((*MockEvent)(nil).AggregateID))
}

// Version mocks base method
func (m *MockEvent) Version() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(int)
	return ret0
}

// Version indicates an expected call of Version
func (mr *MockEventMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockEvent)(nil).Version))
}
